resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - .key-server.conf
  name: key-server-config

secretGenerator:
- envs:
  - .ca.secrets
  name: kmra-secrets

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: intel/trusted-attestation-controller
  newTag: latest
- name: kmra-plugin
  newName: intel/trusted-attestation-controller
  newTag: latest
