apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      # The data in the secret are base64 encoded.
      # km-wrap expects them in PEM encoding.
      # So, we first decode them in the init container
      # before starting the actual controller container.
      initContainers:
      - name: decode-secrets
        image: busybox
        command: ['sh', '-c', 'set -x; chown -R 5000:5000 /registration /plugins']
        volumeMounts:
        - name: plugin-socket-dir
          mountPath: /plugins
        - name: registry-socket-dir
          mountPath: /registration
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --leader-elect
        - --registration-path=/registration/controller.sock
        image: controller:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - name: plugin-socket-dir
          mountPath: /plugins
        - name: registry-socket-dir
          mountPath: /registration
      serviceAccountName: svcact
      terminationGracePeriodSeconds: 10
      volumes:
      - name: plugin-socket-dir
        emptyDir: {}
      - name: registry-socket-dir
        emptyDir: {}
