
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - tcs.intel.com
  resources:
  - quoteattestations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tcs.intel.com
  resources:
  - quoteattestations/finalizers
  verbs:
  - update
- apiGroups:
  - tcs.intel.com
  resources:
  - quoteattestations/status
  verbs:
  - get
  - patch
  - update
